services:
  candle_ros2_node:
    build: ./candle_ros2_node
    container_name: candle_ros2_node
    restart: "no"
    user: "${UID:-1000}:${GID:-1000}"
    group_add:
      - dialout
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    privileged: true 
    network_mode: host 
    volumes:
      - /dev/shm:/dev/shm
      - /run/udev:/run/udev:rw
    environment:
      - ROS_DOMAIN_ID=0

  micro_ros_agent:
    build: ./micro_ros_agent
    container_name: micro_ros_agent
    restart: always
    user: "${UID:-1000}:${GID:-1000}"
    group_add:
      - dialout
    devices:
      - /dev/ttyACM1:/dev/ttyACM1
    privileged: true 
    network_mode: host 
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - ROS_DOMAIN_ID=0
    depends_on:
      - candle_ros2_node

  joy_node:
    build: ./joystick_driver_node
    container_name: joy_linux
    restart: always
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - /dev/input:/dev/input:ro
      - /dev/shm:/dev/shm
    network_mode: host
    privileged: true
    environment:
      - ROS_DOMAIN_ID=0
    depends_on:
      - candle_ros2_node

  foxglove_bridge_agent:
    build: ./foxglove_bridge_agent
    container_name: foxglove_bridge_agent
    restart: always
    user: "${UID:-1000}:${GID:-1000}"
    network_mode: host
    privileged: false
    environment:
      - ROS_DOMAIN_ID=0
    depends_on:
      - candle_ros2_node
